services:
  triton:
    build:
      context: .
      dockerfile: Dockerfile.triton
    shm_size: '4gb'
    volumes:
      - ${PWD}/realistic_onnx:/models
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/v2/health/ready"]
      interval: 60s
      timeout: 5s
      retries: 2
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]
    command: tritonserver --model-repository=/models --http-port 7000 --grpc-port 7001 --metrics-port 7002
